name       : kwidgetsaddons
version    : 5.72.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kwidgetsaddons-5.72.0.tar.xz : a7d6f63951b776ca552c4051147a6bbb416f996561f639c3a41946734853e486
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
