name       : kwidgetsaddons
version    : 5.83.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kwidgetsaddons-5.83.0.tar.xz : 4523d36acdc964a49e8cb2ec31386a1e64357105354351a257fb685dc6f4411d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
