name       : kwidgetsaddons
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/kwidgetsaddons-5.39.0.tar.xz : abb9556d3716beff74460bfea9a33e6470386cb1a68601263b7997a09f1a0db4
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
