name       : kwidgetsaddons
version    : 5.51.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kwidgetsaddons-5.51.0.tar.xz : 57749b54dbba3a347713cfd242cbdda704a64cdeb56dbbbe225c227053fe3e13
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
