name       : kwidgetsaddons
version    : 5.35.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.35/kwidgetsaddons-5.35.0.tar.xz : b3465ad5db2ab8ade8f7e8edb7f66cc8ec1d10b5b8f9b5555c6b76f46b55d681
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
