name       : kwidgetsaddons
version    : 5.62.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kwidgetsaddons-5.62.0.tar.xz : 3a8e75d544783a1f567016f2669c3cfdbf2809b0a3d25afd03d38af62a493671
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
