name       : kwidgetsaddons
version    : 5.50.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kwidgetsaddons-5.50.0.tar.xz : 9530ef4e578859e4dcd1a34f396e552221cbc33fa9f9cb9b1c60ca5dc20a6d7b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
