name       : kwidgetsaddons
version    : 5.55.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kwidgetsaddons-5.55.0.tar.xz : ec5b7ffd47c2b26763e363f741f0d57d280330fdc32c061896bdc32cebdeeb4e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
