name       : kwidgetsaddons
version    : 5.69.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kwidgetsaddons-5.69.0.tar.xz : 5fcc39eb17d832a14e8c2fe98ff26a300aa5c88013c63bcf8eef0017ca4eaf37
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
