name       : kwidgetsaddons
version    : 5.53.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kwidgetsaddons-5.53.0.tar.xz : ac92cb9b745664292efac832f6b104d398f0f9e88f54a42f69bfbd7fd91b3ecd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
