name       : kwidgetsaddons
version    : 5.70.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kwidgetsaddons-5.70.0.tar.xz : d294984b6a3f96459ec505002c3379bde862cf16d914e5f03dd7a620203d830e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
