name       : kwidgetsaddons
version    : 5.68.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kwidgetsaddons-5.68.0.tar.xz : b4ff96b4ec6365e5f9e4da5e651da99be491799a4e6cfd982d0838dda39844ac
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
