name       : kwidgetsaddons
version    : 5.64.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kwidgetsaddons-5.64.0.tar.xz : a2d4a47489621d095c4979ea25d5d8304cf4004b10a892a2b314d74cd30cb5da
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
