name       : kwidgetsaddons
version    : 5.47.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kwidgetsaddons-5.47.0.tar.xz : 5aa6f4002e6f1302f272b3839513debefafd51b7f3a9249f6ef2c5f30cec5a34
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
