name       : kwidgetsaddons
version    : 5.74.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kwidgetsaddons-5.74.0.tar.xz : 5b61c13a6ebb1e248fe38bd3912919f4bf6be93d74bb2f8b1d97caf6dd9a2342
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
