name       : kwidgetsaddons
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/kwidgetsaddons-5.28.0.tar.xz : d6f2e630038976b4eae4b1a510560a3af013c3c21ce88e07a88b5fbe58d042dc
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
