name       : kwidgetsaddons
version    : 5.71.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kwidgetsaddons-5.71.0.tar.xz : 897077995bcf4125d0f90d2964500e718d2a3fd5f117e1b7906177ad13a5082e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
