name       : kwidgetsaddons
version    : 5.76.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kwidgetsaddons-5.76.0.tar.xz : ab7aa94bb1f63e5bea5cf461349c1add96fd608a73c5b7c9d374e6bf035fcac6
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
