name       : kwidgetsaddons
version    : 5.63.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kwidgetsaddons-5.63.0.tar.xz : cce332723324bf3991dc6e6ad8994ff96aae243631f7b4449505fb39f6d8efdb
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Large set of desktop widgets.
description: |
    Large set of desktop widgets.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
